# Generated by Django 3.1.3 on 2020-11-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(upload_to='./lessons_image', verbose_name='image'),
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='Lesson',
        ),
    ]
