# Generated by Django 3.1.3 on 2020-11-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20201111_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson'},
        ),
    ]
